#!/usr/bin/env python3

import sys
import random

#argument checks
if len(sys.argv) <=1:
    print("Monty Hall Problem Simulator")
    print("Usage: monty num_tests")
    sys.exit(1)

if len(sys.argv) >=3:
    print("Too many arguments.")
    print("Usage: monty num_tests")
    sys.exit(1)

#test if argument is int
num=sys.argv[1]

try:
    num=int(num)
except ValueError:
    print("Number of tests is not an integer.")
    print("Usage: monty num_tests")
    sys.exit(3)

#count variables
stay_count=0
switch_count=0

for x in range(0,num):

    #create array with 3 doors and shuffle the order
    #we will assume doors[0] contains the car and 
    #doors[1] and [2] contain goats
    doors=[1,2,3]
    random.shuffle(doors)

    #create user guess of door 1-3 inclusive
    door_guess=random.randint(1,3)

    #Monty will now reveal a door that is not the user's guess
    #nor the car. We can assume doors[1] or doors[2] will be revealed.
    #From implementation view, either the user's guess was initally right
    # and should stay or the user should switch their guess.

    #if the user guesses the door held in doors[0], stay
    #otherwise switch doors
    if door_guess == doors[0]:
        stay_count+=1
    else:
        switch_count+=1

#print("switch",switch_count)
#print("stay",stay_count)

print("Switch would win %.2f percent of experiments"%(switch_count/num))
print("Stay would win %.2f percent of experiments"%(stay_count/num))

sys.exit(0)
