#!/usr/bin/env python3
import sys

#argument checks
if len(sys.argv) <= 1:
    print("Computes Riemann Zeta function approximated z(x,n)")
    print("Usage: ./zeta x n")
    sys.exit(1)

if len(sys.argv) >= 4:
    print("Too many arguments.")
    print("Usage: ./zeta x n")
    sys.exit(2)

if len(sys.argv) == 2:
    print("Need one more argument.")
    print("Usage: ./zeta x n")
    sys.exit(3)

#set variables
x=sys.argv[1]
n=sys.argv[2]
total=0

#integer checks
try:
    x=int(x)
except ValueError:
    print("First argument \""+x+"\" is not an integer.")
    sys.exit(4)

try:
    n=int(n)
except ValueError:
    print("Second argument \""+n+"\" is not an integer.")
    sys.exit(5)

#algorithm compute and print
for num in range(1,n+1):
    total+=(1/num)**x

print("z(%d)=%.6f when approximated at n=%d"%(x,total,n))

sys.exit(0)
