#!/bin/bash

#Will Luttmann - cs571 - week8

#default parameters
startDirectory=`pwd`
fileName=".zoo_num"


#check parameters

if [ $# -eq 0 ]; then
	echo "Usage: ./zoo_count [-f filename] [start_directory] measurement"
	exit 1
fi

if [ $# -ge 5 ]; then
	echo "Too many parameters..."
	echo "Usage: ./zoo_count [-f filename] [start_directory] measurement"
	exit 2
fi

if [ $# -eq 4 ]; then
	if [ $1 == "-f" ]; then
		fileName=$2
		startDirectory=$3
		measurment=$4
	fi
	if [ $2 == "-f" ]; then
		startDirectory=$1
		fileName=$3
		measurment=$4
	fi
	if [ $1 != "-f" ] && [ $2 != "-f" ]; then
		echo "Incorrect parameter entry..."
		echo "Usage: ./zoo_count [-f filename] [start_directory] measurement"
		exit 4
	fi
fi

if [ $# -eq 3 ]; then
	if [ $1 != "-f" ]; then
		echo "Incorrect parameter entry..."
		echo "Usage: ./zoo_count [-f filename] [start_directory] measurement"
		exit 3
	else
		fileName=$2
		measurment=$3
	fi
fi

if [ $# -eq 2 ]; then
	startDirectory=$1
	measurment=$2
fi

if [ $# -eq 1 ]; then
       measurment=$1
fi       

########test variable#############
#echo "fileName = $fileName"
#echo "startDirectory = $startDirectory"
#echo "measurment = $measurment"
###################################

#test if variables are valid

if [ "${measurment}" != "bear" ] && [ "${measurment}" != "dromedary" ] && [ "${measurment}" != "aardvark" ] && [ "${measurment}" != "genet" ] && [ "${measurment}" != "lemur" ]; then
	echo "Incorrect parameter entry..."
	echo "Usage: ./zoo_count [-f filename] [start_directory] measurement"
	echo "Valid measurements are bear, dromedary, aardvark, genet, lemur"
	exit 5
fi


if [ ! -d "$startDirectory" ]; then
	echo "$startDirectory is not a valid directory..."
	exit 6
fi


cd $startDirectory
DIR=( "$startDirectory" )
while (( ${#DIR[@]} > 0 )); do
	workingDIR=${DIR[0]}
	echo "In Folder: $workingDIR"
	#loop in all directories
  	for entry in `ls -A`; do
  		path="$workingDIR/$entry"
  		if [ -d "$path" ]; then
			DIR=( "${DIR[@]}" "$path" )
			echo "in -d"
  		fi
  		if [ -f "$path" ]; then
  			echo "File: $path"
			echo "in -f"
  		fi
  	done
	DIR=( "${DIR[@]:1}" )
done

	
exit 0
